In [2]:
#2 Задание
import numpy as np

def generate_random_matrix(m, n, min_limit=0, max_limit=10):
    return np.random.randint(min_limit, max_limit, size=(m, n))

m = int(input())
n = int(input())
min_limit = int(input())
max_limit = int(input())

random_matrix = generate_random_matrix(m, n, min_limit, max_limit)
print(random_matrix)


 3
 3
 2
 10


[[7 9 6]
 [5 2 4]
 [7 7 3]]


In [1]:
#3 Zadaniye
import numpy as np
import time

def selection_sort(matrix):
    for row in matrix:
        for i in range(len(row)):
            min_index = i
            for j in range(i+1, len(row)):
                if row[j] < row[min_index]:
                    min_index = j
            row[i], row[min_index] = row[min_index], row[i]
    return matrix

# Пример использования
matrix = np.random.randint(0, 100, size=(5, 5))
print("Исходная матрица:")
print(matrix)

start_time = time.time()
sorted_matrix = selection_sort(matrix.copy())
print("Отсортированная матрица:")
print(sorted_matrix)
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))


Исходная матрица:
[[ 6 81 79 94 47]
 [45 79 38 50 21]
 [ 8 76 71 88 22]
 [78 30 64 54 54]
 [41 77 99  3 42]]
Отсортированная матрица:
[[ 6 47 79 81 94]
 [21 38 45 50 79]
 [ 8 22 71 76 88]
 [30 54 54 64 78]
 [ 3 41 42 77 99]]
--- 0 ms ---


In [2]:
# Сортировка вставкой
import numpy as np
import time

def insertion_sort(matrix):
    for row in matrix:
        for i in range(1, len(row)):
            key = row[i]
            j = i - 1
            while j >= 0 and key < row[j]:
                row[j + 1] = row[j]
                j -= 1
            row[j + 1] = key
    return matrix

# Пример использования
matrix = np.random.randint(0, 100, size=(5, 5))
print("Исходная матрица:")
print(matrix)

start_time = time.time()
sorted_matrix = insertion_sort(matrix.copy())
print("Отсортированная матрица:")
print(sorted_matrix)
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))


Исходная матрица:
[[76 99 71 99 22]
 [84 86 70 41 89]
 [22 21 96 20 97]
 [69  7 77 38 93]
 [11  7 39  8 80]]
Отсортированная матрица:
[[22 71 76 99 99]
 [41 70 84 86 89]
 [20 21 22 96 97]
 [ 7 38 69 77 93]
 [ 7  8 11 39 80]]
--- 1 ms ---


In [3]:
# Сортировка пузырьком
import numpy as np
import time

def bubble_sort(matrix):
    for row in matrix:
        n = len(row)
        for i in range(n):
            for j in range(0, n-i-1):
                if row[j] > row[j+1]:
                    row[j], row[j+1] = row[j+1], row[j]
    return matrix

# Пример использования
matrix = np.random.randint(0, 100, size=(5, 5))
print("Исходная матрица:")
print(matrix)

start_time = time.time()
sorted_matrix = bubble_sort(matrix.copy())
print("Отсортированная матрица:")
print(sorted_matrix)
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))


Исходная матрица:
[[87 46 56 96 44]
 [29 98 24 52 12]
 [99 43 45 81  7]
 [26 90 89 46  3]
 [86 67 10 14 52]]
Отсортированная матрица:
[[44 46 56 87 96]
 [12 24 29 52 98]
 [ 7 43 45 81 99]
 [ 3 26 46 89 90]
 [10 14 52 67 86]]
--- 1 ms ---


In [4]:
#Сортировка шелла

import numpy as np
import time

def shell_sort(matrix):
    for row in matrix:
        n = len(row)
        gap = n // 2
        while gap > 0:
            for i in range(gap, n):
                temp = row[i]
                j = i
                while j >= gap and row[j - gap] > temp:
                    row[j] = row[j - gap]
                    j -= gap
                row[j] = temp
            gap //= 2
    return matrix

# Пример использования
matrix = np.random.randint(0, 100, size=(5, 5))
print("Исходная матрица:")
print(matrix)

start_time = time.time()
sorted_matrix = shell_sort(matrix.copy())
print("Отсортированная матрица:")
print(sorted_matrix)
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))


Исходная матрица:
[[64 16 80 79 35]
 [72 95 25 78 91]
 [ 2 37  8 91 32]
 [25 99 53 25 26]
 [56 51 27 64  8]]
Отсортированная матрица:
[[16 35 64 79 80]
 [25 72 78 91 95]
 [ 2  8 32 37 91]
 [25 25 26 53 99]
 [ 8 27 51 56 64]]
--- 1 ms ---


In [5]:
#Быстрая сортировка
import numpy as np
import time

def quick_sort(matrix):
    for i in range(len(matrix)):
        matrix[i] = quick_sort_helper(matrix[i])
    return matrix

def quick_sort_helper(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quick_sort_helper(left) + middle + quick_sort_helper(right)

# Пример использования
matrix = np.random.randint(0, 100, size=(5, 5))
print("Исходная матрица:")
print(matrix)

start_time = time.time()
sorted_matrix = quick_sort(matrix.copy())
print("Отсортированная матрица:")
print(sorted_matrix)
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))


Исходная матрица:
[[41 83 67 63 97]
 [61 62 93  4 10]
 [22 34 94 89 62]
 [25 46 48 20  1]
 [45 30 54 93 27]]
Отсортированная матрица:
[[41 63 67 83 97]
 [ 4 10 61 62 93]
 [22 34 62 89 94]
 [ 1 20 25 46 48]
 [27 30 45 54 93]]
--- 0 ms ---


In [6]:
#Турирная сортировка
import numpy as np
import time

def tournament_sort(matrix):
    for i in range(len(matrix)):
        matrix[i] = tournament_sort_helper(matrix[i])
    return matrix

def tournament_sort_helper(arr):
    n = len(arr)
    tree = [None] * (2 * n)
    for i in range(n):
        tree[n + i] = (arr[i], i)
    for i in range(n - 1, 0, -1):
        tree[i] = min(tree[2 * i], tree[2 * i + 1])
    sorted_arr = []
    for _ in range(n):
        min_val, min_index = tree[1]
        sorted_arr.append(min_val)
        tree[n + min_index] = (float('inf'), min_index)
        min_index += n
        while min_index > 1:
            min_index //= 2
            tree[min_index] = min(tree[2 * min_index], tree[2 * min_index + 1])
    return sorted_arr

# Пример использования
matrix = np.random.randint(0, 100, size=(5, 5))
print("Исходная матрица:")
print(matrix)

start_time = time.time()
sorted_matrix = tournament_sort(matrix.copy())
print("Отсортированная матрица:")
print(sorted_matrix)
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))


Исходная матрица:
[[53 37 65 48 25]
 [50 78 20 55 39]
 [55  4 18 32 95]
 [86 55 72 25 88]
 [56 67 14 95 81]]
Отсортированная матрица:
[[25 37 48 53 65]
 [20 39 50 55 78]
 [ 4 18 32 55 95]
 [25 55 72 86 88]
 [14 56 67 81 95]]
--- 1 ms ---
